server:
  port: 8084


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ShService
    username: root
    password: root
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties.hibernate:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect


  application:
    name: ShippingService


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defalutZone: http://localhost:8761/eureka